### ISSUE TITLE
youtube video is loading too slowly

### ISSUE THREAD

**Issue by lotusgraham** [lotusgraham/MeditationApp123#5]
can we make the youtube video load faster?

**Comment by SirusCodes** [comment]
what do u think what are possible solutions?

**Comment by lotusgraham** [comment]
it has to be in the package we are using.. this youtube video explains a good way to building this functionality.. i think we could extract a good solution from here. @SirusCodes https://www.youtube.com/watch?v=feQhHStBVLE

**Comment by SirusCodes** [comment]
@lotusgraham this is an overkill ig and we are not autoplaying the video so it's fine ig
